[project]
name = "r2e-gym"
version = "0.1.0"
authors = [
    {name = "Naman Jain", email = "naman1205jain@gmail.com"},
    {name = "Jaskirat Singh", email = "jaskirat.singh@anu.edu.au"},
]
dependencies = [
    "pandas==2.3.3",
    "tqdm==4.67.1",
    "asttokens==3.0.1",
    "pydantic==2.12.5",
    "matplotlib==3.10.8",
    "numpy==2.4.1",
    "datasets==2.19.0",
    "ipython==9.9.0",
    "pygments==2.19.2",
    "flask==3.1.2",
    "gym==0.26.2",
    "fire==0.7.1",
    "diff-parser==1.1",
    "scikit-learn==1.8.0",
    "rich==14.2.0",
    "simple-parsing==0.1.7",
    "together==1.5.34",
    "markdown==3.10",
    "transformers==4.57.3",
    "pexpect==4.9.0",
    "libtmux==0.53.0",
    "bashlex==0.18",
    "anthropic[vertex]==0.43.0",
    "litellm==1.80.13",
    "google-cloud-aiplatform==1.133.0",
    "swebench==3.0.2",
    "apscheduler==3.11.2",
    "sb-cli==0.1.5",
    "seaborn==0.13.2",
    "kubernetes==34.1.0",
    "gpustat==1.1.1",
    "orjson==3.11.5",
    "cryptography>=44.0.0",
]
requires-python = ">=3.10"
readme = "README.md"

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
